result: FrequentPatternCompressor.cpp main.cpp Node.cpp PrefixSpan.cpp Trie.cpp Utils.cpp libsnappy.a
		g++-5 -o result FrequentPatternCompressor.cpp main.cpp Node.cpp PrefixSpan.cpp Trie.cpp Utils.cpp  -std=c++11 -O3 
